In [1]:
# import library
import pandas as pd 
import joblib

from sklearn.model_selection import train_test_split

In [2]:
# read data function
def read_data(file_path_name, ind_col):
  data = pd.read_csv(file_path_name, index_col=ind_col)
  print('shape :', data.shape)
  return data

In [ ]:
# show shape of data
data = read_data('data/raw/data.csv', 0)

shape : (150000, 11)

In [ ]:
# show the five rows of data
data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [5]:
# data shape
data.shape

(150000, 11)

In [ ]:
# statistical summary of data
data.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [7]:
# split input output function
def split_input_output(dataset, target_var):
  y = dataset[target_var]
  X = data.drop(target_var, axis=1)
  
  print('shape X:', X.shape)
  print('shape y:', y.shape)
  
  joblib.dump(X, 'data/output/input.pkl')
  joblib.dump(y, 'data/output/output.pkl')

In [ ]:
# define target variable
TARGET_VAR = 'SeriousDlqin2yrs'

# running the split input output function
split_input_output(data, TARGET_VAR)

shape X: (150000, 10)
shape y: (150000,)

In [9]:
# split train test function
def split_train_test(data_x, data_y, size_test, size_valid):
  X_train, X_test, y_train, y_test = train_test_split(data_x, data_y, 
                                                      test_size = size_test, random_state=42)
  X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, 
                                                        test_size = size_valid, random_state=42)
  
  print('X_train shape :', X_train.shape)
  print('y_train shape :', y_train.shape)
  print('X_valid shape :', X_valid.shape)
  print('y_valid shape :', y_valid.shape)
  print('X_test shape :', X_test.shape)
  print('y_test shape :', y_test.shape)
  
  joblib.dump(X_train, 'data/output/X_train.pkl')
  joblib.dump(y_train, 'data/output/y_train.pkl')
  joblib.dump(X_valid, 'data/output/X_valid.pkl')
  joblib.dump(y_valid, 'data/output/y_valid.pkl')
  joblib.dump(X_test, 'data/output/X_test.pkl')
  joblib.dump(y_test, 'data/output/y_test.pkl')

In [ ]:
# load X and y data 
X = joblib.load('data/output/input.pkl')
y = joblib.load('data/output/output.pkl')

# running the split train test function
split_train_test(X, y, 0.2, 0.2)

X_train shape : (96000, 10)
y_train shape : (96000,)
X_valid shape : (24000, 10)
y_valid shape : (24000,)
X_test shape : (30000, 10)
y_test shape : (30000,)